name: Deploy_to_Internal_Test 
run-name: Deploy to Internal Test 📱
on: 
    workflow_dispatch: 
jobs:
    BuildCredentiatedApp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                path: 'source'
            - name: Checkout configuration Repository
              uses: actions/checkout@v4
              with:
                repository: Dragon-Memory-Team/DragonMemoy-App-Configs
                token: ${{ secrets.PAT }}
                path: settings
            - name: Remove placeholder settings
              run: rm ./source/eas.json ./source/credentials.json
            - name: Copy the correct settings
              run: cp -r ./settings/android ./source && cp ./settings/credentials.json ./source && cp ./settings/eas.json ./source
            - name: Zip source code
              run: zip -r DragonMemoryCredentiaded.zip ./source
            - name: 'Upload Source Code with real credentials'
              uses: actions/upload-artifact@v4
              with:
                name: DragonMemoryCredentiated
                path: ./DragonMemoryCredentiaded.zip
                retention-days: 1
    EasBuild:
        needs: [BuildCredentiatedApp]
        runs-on: ubuntu-latest
        steps:
            - name: Download Credentiaded Application Zip
              uses: actions/download-artifact@v4
              with:
                name: DragonMemoryCredentiated
            - name: Unzip Artifacts
              run: unzip ./DragonMemoryCredentiaded.zip
            - name: Setup Node Environment
              uses: actions/setup-node@v4
              with:
                node-version: '20.13.1'
            - name: Install Node Dependencies
              working-directory: source
              run: npm install
            - name: Install EAS Cli Tool
              run: npm install --global eas-cli