name: Deploy_to_Internal_Test 
run-name: Deploy to Internal Test 📱
on: 
    workflow_dispatch: 
jobs:
    BuildApplication:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node Environment
              uses: actions/setup-node@v4
              with:
                node-version: '20.13.1'
            - name: Install Dependencies
              run: npm install
            - name: Install EAS
              run: npm install --global eas-cli
            - name: Checkout configuration Repository
              uses: actions/checkout@v4
              with:
                repository: Dragon-Memory-Team/DragonMemoy-App-Configs
                token: ${{ secrets.PAT }}
            - name: Show all
              run: ls
